import { DefaultReporter } from 'vitest/reporters';

/**
 * This reporter provides a real-time progress summary during test execution and
 * reports failures in detail but avoids printing a list of successful tests.
 * For context see https://github.com/vitest-dev/vitest/issues/7881
 */
export class SummaryReporter extends DefaultReporter {
  onTestModuleEnd() {
    // Override this method to suppress individual file results
  }
}

/**
 * These configuration options for `babel-plugin-istanbul` need to match the
 * values set by Vitest internally, so that it picks the coverage
 * instrumentation generated by said babel plugin instead of trying to generate
 * its own.
 *
 * See https://github.com/vitest-dev/vitest/discussions/7841#discussioncomment-12855608
 */
export const vitestCoverageOptions = {
  coverageGlobalScope: 'globalThis',
  coverageVariable: '__VITEST_COVERAGE__',
};
