name: Continuous integration
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache the node_modules dir
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
    - name: Install
      run: yarn install --immutable
    - name: Format
      run: yarn checkformatting
    - name: Build
      run: |
        yarn build
